project_name: sss

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
    format_overrides:
      - goos: windows
        format: zip

upx:
  - enabled: true
    compress: best
    brute: true
    lzma: true


checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^ci:"
      - "^Merge pull request"